export default {
  APPOINTMENTS_REQUEST: '@APPOINTMENTS/APPOINTMENTS_REQUEST',
  APPOINTMENTS_SUCCESS: '@APPOINTMENTS/APPOINTMENTS_SUCCESS',
  APPOINTMENTS_FAILURE: '@APPOINTMENTS/APPOINTMENTS_FAILURE',
};
